############################################################
# +------------------------------------------------------+ #
# |                    STORMS FREEZE                     | #
# +------------------------------------------------------+ #
############################################################

PREFIX: "&7[&6StormsFreeze&7]"
COLOR-TARGET: "&e"
RELOAD-MESSAGE: " &aThe plugin was reloaded correctly"
CONSOLE-MESSAGE: "Commands are only executed in game"
MESSAGE-NOT-PERMISSION: "&cYou do not have permissions for this command"

############################################################
# +------------------------------------------------------+ #
# |                   TITLE MESSAGE                      | #
# +------------------------------------------------------+ #
############################################################

TITLES:
  FROZED:
    TITLE: "&cYou were frozen"
    SUBTITLE: "&efollow the instructions of the staff"

  UNFROZED:
    TITLE: "&aYou were thawed"
    SUBTITLE: "&cthanks for the copearion"

############################################################
# +------------------------------------------------------+ #
# |                MESSAGES IN THE CHAT                  | #
# +------------------------------------------------------+ #
############################################################

FROZZED-MESSAGE: "&cYou're frozen, you can't move"
STAFF-FROZZED-MESSAGE: " You froze to "
STAFF-UNFROZZED-MESSAGE: " &aDefrost at "

############################################################
# +------------------------------------------------------+ #
# |                    PARTICLES                         | #
# +------------------------------------------------------+ #
############################################################

PARTICLES:
  TYPE: "SNOW_SHOVEL"
  AMOUNT: 50

# More Particles: https://minecraft.fandom.com/wiki/Particles

############################################################
# +------------------------------------------------------+ #
# |                      CREDITS                         | #
# +------------------------------------------------------+ #
############################################################

COMMANDS-LIST:
  - "sw leave"
  - "me gaaaaaaaaaaaaaaa"

COMMANDS-BLOCK:
  - "/sw"
  - "/SW"