############################################################
# +------------------------------------------------------+ #
# |                    STORMS FREEZE                     | #
# +------------------------------------------------------+ #
############################################################

# This is the first public version of the plugin, any bugs
# or new suggestions can be made via my discord or a comment
# on spigot.

# Discord: myclass#9779
# Spigot:
# Portfolio: https://anhuar.space

############################################################
# +------------------------------------------------------+ #
# |                     CHAT ACTIONS                     | #
# +------------------------------------------------------+ #
############################################################

CHAT:
  NO-PERMISSIONS: "&8(&eStormFreeze&8) &cYou don't have access to this."

  CHAT-CREATED: "&8(&eFreezeChat&8) &aThe chat was created successfully."
  CHAT-DELETED: "&8(&eFreezeChat&8) &cThe chat was successfully deleted."

  SEND-FORMAT: "&8(&eFreezeChat&8) &aYou: &7<he_name> &8➼ &cHe: &7<you_name> &8➼ &e<message>."
  RECEIVED-FORMAT: "&8(&eFreezeChat&8) &cHe: &7<he_name> &8➼ &aYou: &7<you_name> &8➼ &e<message>."

  FROZZED-MESSAGE: "&8(&eStormFreeze&8) &cYou're frozen, you can't move."

  STAFF-FROZZED-MESSAGE: "&8(&eStormFreeze&8) &aYou froze to &e<target_name>."
  STAFF-UNFROZZED-MESSAGE: "&8(&eStormFreeze&8) &cDefrost at &e<target_name>."

############################################################
# +------------------------------------------------------+ #
# |                    TITLE ACTIONS                     | #
# +------------------------------------------------------+ #
############################################################

TITLES:
  FROZED:
    TITLE: "&cYou were frozen"
    SUBTITLE: "&efollow the instructions of the staff"

  UNFROZED:
    TITLE: "&aYou were thawed"
    SUBTITLE: "&cthanks for the copearion"

############################################################
# +------------------------------------------------------+ #
# |                   COMMANDS ACTIONS                   | #
# +------------------------------------------------------+ #
############################################################

COMMANDS:
  FORCE-EJECUTE:
    - "sw leave"
    - "sprac leave"

  DENY-EJECUTE:
    - "/sw"
    - "/SW"
    - "/pay"
    - "/PAY"

############################################################
# +------------------------------------------------------+ #
# |               FREEZE PLAYER ACTIONS                  | #
# +------------------------------------------------------+ #
############################################################

PARTICLES:
  TYPE: "SNOW_SHOVEL"
  AMOUNT: 50

# More Particles: https://minecraft.fandom.com/wiki/Particles

HEAD-ITEM:
  TYPE: ICE
  DATA: 0

# More Items: https://minecraft-ids.grahamedgecombe.com/

BANNED-PLAYER:
  ACTIVE: true
  COMMAND: "ban"
  REASON: "Testing reason."