name: Jails
version: '${project.version}'
main: myclass.jails.Main
api-version: 1.19
authors: [ myclass ]

commands:
  freeze:
    description: command freeze
  ss:
    description: command freeze 2
  setjail:
    description: 2
  setreleased:
    description: asd