name: StormFreeze
version: '${project.version}'
main: myclass.stormfreeze.Main
api-version: 1.19
website: https://myclxss.online
authors: [ myclass ]


commands:
  freeze:
    description: command freeze
  ss:
    description: command freeze 2
  stormfreeze:
    description: main command


permissions:
  stormfreeze.staff:
    description: use commands staff
  stormfreeze.admin:
    description: use commands admin