name: StormFreeze
version: '${project.version}'
main: myclass.stormfreeze.Main
api-version: 1.19
authors: [ myclass ]

commands:
  freeze:
    description: command freeze
  ss:
    description: command freeze 2
  setjail:
    description: 2
  setreleased:
    description: asd
  setred:
    description: asd
  setgreen:
    description: asd222